version: '3.7'
services:
  intelli-judge-application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    container_name: intelli-judge-application
    expose:
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - intelli-judge-network
    depends_on:
      - intelli-judge-database
      - intelli-judge-phpmyadmin
  intelli-judge-database:
    image: mysql:8.0.13
    container_name: intelli-judge-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - intelli-judge-network
  intelli-judge-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: intelli-judge-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - intelli-judge-database
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: intelli-judge-database
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 2048M
    networks:
      - intelli-judge-network

networks:
  intelli-judge-network:
    driver: bridge